/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechef;

import org.junit.Test;
import static org.junit.Assert.*;

public class CrazyCoinsTest {

    @Test public void testChooseM() {
        final var six3 = CrazyCoins.numChooseM(6, 3);
        assertEquals("6 choose 3", 20, six3);
    }

    @Test public void testPermsWithFlips() {
        final var countFor2 = CrazyCoins.numPermsWithFlips(2);
        assertEquals("got expected count", 3, countFor2);
        final var countFor3 = CrazyCoins.numPermsWithFlips(3);
        assertEquals("got expected count", 8, countFor3);
    }
}
